services:
  #  ubl-db:
  #    image: postgres:17.5
  #    container_name: ubl-db
  #    environment:
  #      - POSTGRES_USER=${DATABASE_USER}
  #      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #      - POSTGRES_DB=${DATABASE_NAME}
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - ubl_db_data:/var/lib/postgresql/data
  #    networks:
  #      - ubl-network
  #    restart: on-failure
  #    healthcheck:
  #      test: [ "CMD-SHELL", "pg_isready" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5
  ubl-redis:
    image: redis:8.2.1
    container_name: ubl-redis
    restart: on-failure
    command: redis-server --requirepass 123456 --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - ubl-network
    ports:
      - '6379:6379'

  ubl-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ubl-rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-admin123}
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ubl-network
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672' # Management UI

networks:
  ubl-network:
volumes:
  #  ubl_db_data:
  redis_data:
  rabbitmq_data:
