services:
  ubl-db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: ubl-db_postgis
    environment:
      - POSTGRES_USER=ubl_user
      - POSTGRES_PASSWORD=drp1vgz*uhd-gvy8KDA
      - POSTGRES_DB=ubl_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ubl-network
    restart: on-failure
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  ubl-rabbitmq:
    image: sangdang1/urbanlens-rabbitmq:3.13
    platform: linux/amd64
    container_name: ubl-rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-admin123}
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ubl-network
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672' # Management UI
  ubl-redis:
    image: redis:8.2.1
    platform: linux/amd64
    container_name: ubl-redis
    restart: on-failure
    command: redis-server --requirepass vD6hC@hKD@BP4bBhRVXkW --appendonly yes
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'vD6hC@hKD@BP4bBhRVXkW', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - ubl-network
networks:
  ubl-network:
volumes:
  db_data:
  rabbitmq_data:
  redis_data:
